### ISSUE TITLE
Broken in Veeam 10

### ISSUE THREAD

**Issue by ksd-dannyv** [glukinho/zabbix-veeam-rest#2]
Veeam disabled http access to the API in VBR 10. Simply updating the connection string to include the FQDN and https isn't sufficient to make it work.

**Comment by stdonato** [comment]
Same problem here. Don't work with Veeam 10.

**Comment by stdonato** [comment]
> 
> 
> Veeam disabled http access to the API in VBR 10. Simply updating the connection string to include the FQDN and https isn't sufficient to make it work.

Try this: https://github.com/stdonato/zabbix-veeam-rest

**Comment by ksd-dannyv** [comment]
> Try this: https://github.com/stdonato/zabbix-veeam-rest

Discovery works, but it doesn't get job info.

`2020-04-07 13:13:51 - getLastBackupJobInfo - {"JobName":null,"Result":null,"ResultNum":null,"CreationTime":"2020-04-07 13:13:51","CreationTimeEpoch":1586258031,"EndTime":"2020-04-07 13:13:51","EndTimeEpoch":1586258031,"Duration":0,"Comment":"gets last job info for given JobName"}`

Extracting the raw content I receive a message about a badly formed request.

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">

<HTML><HEAD><TITLE>Bad Request</TITLE>

<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>

<BODY><h2>Bad Request</h2>

<hr><p>HTTP Error 400. The request is badly formed.</p>

</BODY></HTML>
```

**Comment by stdonato** [comment]
Get error for all jobs? Works well with mine. I'll look for bugs. Thanks.

**Comment by stdonato** [comment]
Your jobs have space in name? I have error only in 1 job with space in name.

**Comment by ksd-dannyv** [comment]
> Your jobs have space in name? I have error only in 1 job with space in name.

all my jobs have spaces. Any way to fix?

**Comment by stdonato** [comment]
Well, i'll create a job with spaces to test. I let you know when fixed.

**Comment by ksd-dannyv** [comment]
> Well, i'll create a job with spaces to test. I let you know when fixed.

I understand it's not a priority, but did you have any success in replicating and fixing the issue?

**Comment by glukinho** [comment]
@ksd-dannyv I have recreated the script from scratch to support VBR 10 with HTTPS.
