### ISSUE TITLE
Can't auth via domain login password

### ISSUE THREAD

**Issue by denser** [glukinho/zabbix-veeam-rest#4]
How it mut be filled?

user@domain.com
domain\user

How? 2 theese variants are give me throw 
`PHP Fatal error:  Uncaught VeeamAuthException: X-RestSvcSessionSd is null in /usr/lib/zabbix/externalscripts/zabbix-veeam.php:181`

**Comment by denser** [comment]
`if ($headerArr[0] == 'X-RestSvcSessionId' || $headerArr[0] == 'x-restsvcsessionid') $this->restsvcsessionid = trim($headerArr[1]);`
add lower case in 181 line.

**Comment by glukinho** [comment]
In my environments I use only username without domain name.
